services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-chat-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:alpine
    restart: always
    container_name: redis-container
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
      - '.env'
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/share/nginx/html

  celery_worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    volumes:
      - ./celery:/app

    env_file:
      - .env
    depends_on:
      - redis-cache
      - db

volumes:
  postgres_data:
