services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-chat-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    # expose:
    #   - "8000"
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data:
